// Mocks generated by Mockito 5.0.0 from annotations
// in finance_guru/test/data/financial_data_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:finance_guru/data/source/financial_database_dao.dart' as _i2;
import 'package:finance_guru/model/financial_data_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FinancialDatabaseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinancialDatabaseDao extends _i1.Mock
    implements _i2.FinancialDatabaseDao {
  MockFinancialDatabaseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AssetModel>> fetchAssetModelList() =>
      (super.noSuchMethod(Invocation.method(#fetchAssetModelList, []),
              returnValue: Future.value(<_i4.AssetModel>[]))
          as _i3.Future<List<_i4.AssetModel>>);
}
